import type { Metadata } from "next";
import "./globals.css";
// import KeycloakProvider from "next-auth/providers/keycloak";
import { auth } from '../auth';
import { Navbar } from './_lib/components/Navbar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  return (
    <html lang="en">
      <body>
        <Navbar session={session}/>
        {children}
      </body>
    </html>
  );
}